# cleanup
- name: remove {{ root_folder }}
  file:
    path: "{{ root_folder }}"
    state: absent

- name: Create {{ root_folder }}
  file:
    path: "{{ root_folder }}"
    state: directory
    mode: '0755'

- name: culr {{ groups['wildfly_node_1'][0] }}:8180 and {{ groups['wildfly_node_2'][0] }}:8280
  shell: |
    echo curl -b {{ root_folder }}/cookies1 -c {{ root_folder }}/cookies1 http://{{ groups['wildfly_node_1'][0] }}:8180/clusterbench/session
    echo curl -b {{ root_folder }}/cookies2 -c {{ root_folder }}/cookies2 http://{{ groups['wildfly_node_2'][0] }}:8280/clusterbench/session
    hammerNodes(){
      while true; do
        for mynum in `seq 1 100`; do
          curl -b {{ root_folder }}/cookie-${mynum} -c {{ root_folder }}/cookie-${mynum} http://{{ groups['wildfly_node_1'][0] }}:8180/clusterbench/session
        done
        sleep 1
        for mynum in `seq 1 100`; do
          curl -b {{ root_folder }}/cookie-${mynum} -c {{ root_folder }}/cookie-${mynum} http://{{ groups['wildfly_node_2'][0] }}:8280/clusterbench/session
        done
        sleep 1
      done
    }
    hammerNodes > {{ root_folder }}/client.log 2>&1