{
 "title": "wildfy",
 "description": "Metrics about WildFly Cluster",
 "tags": [
  "grafana",
  "prometheus",
  "wildfly"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wildfy-cpu_process_cpu_load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cpu_process_cpu_load" }
   ],
   "targets": [
    { "expr": "base:cpu_process_cpu_load" },
    {}
   ]
  },
  {
   "title": "wildfy-classloader_total_loaded_class_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    {
     "format": "short",
     "label": "classloader_total_loaded_class_count"
    }
   ],
   "targets": [
    {
     "expr": "base:classloader_total_loaded_class_count"
    },
    {}
   ]
  },
  {
   "title": "wildfy-memory_used_heap_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "memory_used_heap_bytes" }
   ],
   "targets": [
    { "expr": "base:memory_used_heap_bytes" },
    {}
   ]
  },
  {
   "title": "wildfy-memory_used_non_heap_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "memory_used_non_heap_bytes" }
   ],
   "targets": [
    {
     "expr": "base:memory_used_non_heap_bytes"
    },
    {}
   ]
  },
  {
   "title": "wildfy-thread_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "thread_count" }
   ],
   "targets": [
    { "expr": "base:thread_count" },
    {}
   ]
  },
  {
   "title": "wildfy-thread_daemon_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "thread_daemon_count" }
   ],
   "targets": [
    { "expr": "base:thread_daemon_count" },
    {}
   ]
  }
 ]
}