global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: wildfy-1
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:10090']
  - job_name: wildfy-2
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:10190']
  - job_name: wildfy-3
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:10290']
  - job_name: wildfy-4
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:10390']
